In [1]:
import pandas as pd

In [2]:
dataset =pd.read_csv("customer_data.csv")

In [3]:
dataset

,name,age,gender,education,income,country,purchase_frequency,spending
0,Teresa Williams MD,42,Female,High School,53936,Slovenia,0.9,13227.120
1,Christine Myers,49,Female,Master,82468,Aruba,0.6,12674.040
2,Dwayne Moreno,55,Male,Bachelor,56941,Cyprus,0.3,5354.115
3,Amy Norton,24,Female,Bachelor,60651,Palau,0.2,2606.510
4,Tonya Adams,64,Male,Master,81884,Zambia,0.9,18984.780
...,...,...,...,...,...,...,...,...
995,Jason Haas,42,Female,PhD,98170,Bosnia and Herzegovina,0.7,17435.950
996,Sharon Valdez,39,Male,High School,59174,Eritrea,0.9,11662.830
997,Andrew Taylor,50,Male,Master,59808,Serbia,0.4,7196.160
998,Jessica Johnson,50,Female,Master,58272,Cyprus,0.7,13939.520
999,Brian Williams,38,Female,Bachelor,32512,Turkey,0.5,8312.800

In [4]:
dataset = dataset.drop(columns=['name','country'])

In [5]:
dataset

     age  gender    education  income  purchase_frequency   spending
0     42  Female  High School   53936                 0.9  13227.120
1     49  Female       Master   82468                 0.6  12674.040
2     55    Male     Bachelor   56941                 0.3   5354.115
3     24  Female     Bachelor   60651                 0.2   2606.510
4     64    Male       Master   81884                 0.9  18984.780
..   ...     ...          ...     ...                 ...        ...
995   42  Female          PhD   98170                 0.7  17435.950
996   39    Male  High School   59174                 0.9  11662.830
997   50    Male       Master   59808                 0.4   7196.160
998   50  Female       Master   58272                 0.7  13939.520
999   38  Female     Bachelor   32512                 0.5   8312.800

[1000 rows x 6 columns]

In [6]:
dataset =pd.get_dummies(dataset,drop_first=True)

In [7]:
dataset

,age,income,purchase_frequency,spending,gender_Male,education_High School,education_Master,education_PhD
0,42,53936,0.9,13227.120,False,True,False,False
1,49,82468,0.6,12674.040,False,False,True,False
2,55,56941,0.3,5354.115,True,False,False,False
3,24,60651,0.2,2606.510,False,False,False,False
4,64,81884,0.9,18984.780,True,False,True,False
...,...,...,...,...,...,...,...,...
995,42,98170,0.7,17435.950,False,False,False,True
996,39,59174,0.9,11662.830,True,True,False,False
997,50,59808,0.4,7196.160,True,False,True,False
998,50,58272,0.7,13939.520,False,False,True,False
999,38,32512,0.5,8312.800,False,False,False,False

In [8]:
dataset.columns

Index(['age', 'income', 'purchase_frequency', 'spending', 'gender_Male',
       'education_High School', 'education_Master', 'education_PhD'],
      dtype='str')

In [9]:
x = dataset[['age', 'income', 'purchase_frequency','gender_Male',
       'education_High School', 'education_Master', 'education_PhD']]

In [10]:
x

,age,income,purchase_frequency,gender_Male,education_High School,education_Master,education_PhD
0,42,53936,0.9,False,True,False,False
1,49,82468,0.6,False,False,True,False
2,55,56941,0.3,True,False,False,False
3,24,60651,0.2,False,False,False,False
4,64,81884,0.9,True,False,True,False
...,...,...,...,...,...,...,...
995,42,98170,0.7,False,False,False,True
996,39,59174,0.9,True,True,False,False
997,50,59808,0.4,True,False,True,False
998,50,58272,0.7,False,False,True,False
999,38,32512,0.5,False,False,False,False

In [11]:
y=dataset[[ 'spending']]

In [12]:
y

      spending
0    13227.120
1    12674.040
2     5354.115
3     2606.510
4    18984.780
..         ...
995  17435.950
996  11662.830
997   7196.160
998  13939.520
999   8312.800

[1000 rows x 1 columns]

In [13]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

x_train, x_test, y_train, y_test = train_test_split(
    x, y, test_size=0.2, random_state=11
)

In [14]:
from sklearn.linear_model import LinearRegression 
regressor=LinearRegression() 
regressor.fit(x_train,y_train)

LinearRegression()

In [15]:
y_pred=regressor.predict(x_test) 
y_pred

array([[ 4862.43499175],
       [13098.30684257],
       [ 2144.68987948],
       [ 7277.97092924],
       [12170.81292986],
       [10032.22112042],
       [ 5264.96697899],
       [13586.71376544],
       [13821.5842504 ],
       [17420.50795696],
       [10118.94732801],
       [ 6344.36643299],
       [ 4283.9440202 ],
       [ 3346.12074938],
       [ 2942.76670021],
       [ 9452.16876726],
       [ 8960.02901051],
       [12582.88718663],
       [ 6602.96795627],
       [ 6386.51625093],
       [17339.52586913],
       [14583.38263409],
       [ 9092.74583619],
       [10694.37227735],
       [12763.32792879],
       [ 7993.05783376],
       [ 1733.22311112],
       [14244.64786799],
       [10524.11672637],
       [ 5662.2749173 ],
       [11110.40008452],
       [ 8360.28322127],
       [15908.24343307],
       [10894.11436383],
       [ 9262.92773332],
       [16614.61988497],
       [17647.46720297],
       [20322.77056991],
       [16286.08899918],
       [12807.8561    ],
       [ 4613.86508682],
       [18478.4610011 ],
       [ 2500.57631383],
       [10780.45576208],
       [ 3973.82705442],
       [14665.42759451],
       [ 4168.48829167],
       [ 4058.2021349 ],
       [ 7849.7440326 ],
       [ 5824.44620566],
       [12231.3005546 ],
       [ 9920.43033149],
       [17390.44469899],
       [ 5067.01611779],
       [ 4467.10357261],
       [ 2540.90719445],
       [ 5093.28086965],
       [ 5567.88339079],
       [14589.44458977],
       [ 4463.47242507],
       [ 6626.69993792],
       [11397.68465312],
       [ 5012.48762489],
       [ 7016.22062669],
       [15843.44594162],
       [-1624.95459217],
       [ 1537.91646027],
       [ 3590.73657323],
       [ 4512.41352017],
       [ 4605.33172326],
       [14644.4661771 ],
       [ 6467.48152879],
       [11678.90080293],
       [17750.00178399],
       [14476.86155003],
       [ 4951.37879112],
       [ 5141.49636186],
       [16014.79414361],
       [ 9741.4786027 ],
       [ 5981.21106387],
       [ 6568.41659849],
       [15881.09846287],
       [13482.10130508],
       [ 4762.40963789],
       [ 1936.52353834],
       [ 5230.7180371 ],
       [ 5626.29521296],
       [ 8223.48344912],
       [-3053.70809083],
       [ 6563.07519986],
       [ 6480.11580298],
       [11217.53535795],
       [ 6835.32120726],
       [   88.66737164],
       [13533.87810445],
       [ 4467.93206449],
       [ 4381.26824949],
       [10454.36818601],
       [11502.78253304],
       [15518.12863697],
       [ 6346.66741573],
       [14016.12425868],
       [ 1720.37223842],
       [-1878.63796238],
       [ 8313.44641233],
       [ 5539.62910465],
       [ 7198.33673826],
       [ 8108.81341353],
       [19222.33446966],
       [12247.97089755],
       [ 9106.14202857],
       [ 5334.13721888],
       [13488.05995991],
       [10645.94996213],
       [ 9700.18078733],
       [10244.16970717],
       [18603.89358151],
       [20603.36026893],
       [ 8422.79019914],
       [15885.77547553],
       [ -605.0717867 ],
       [ 6942.00847205],
       [ 3811.03935499],
       [12168.32808087],
       [ 5209.15004354],
       [ 7782.99642846],
       [15820.5790554 ],
       [11098.30717421],
       [ 1657.6542507 ],
       [ 8337.79102212],
       [ 9227.79155491],
       [ 5581.11094243],
       [11824.19784067],
       [14765.49698188],
       [15766.31493898],
       [-3489.93575583],
       [ 1686.22494906],
       [15564.12944598],
       [11788.51670994],
       [ 6517.29761584],
       [18771.94630182],
       [ 2174.93376021],
       [ 5280.93775212],
       [16616.22848086],
       [12995.74123408],
       [14107.94704046],
       [14344.81443198],
       [ 7438.63297288],
       [ -277.65547036],
       [15095.63060582],
       [ 2276.04974356],
       [ 5236.47074575],
       [ 7103.87688763],
       [ 7661.65984013],
       [14594.6483168 ],
       [ 8507.1046188 ],
       [ 9236.9234704 ],
       [16493.10602702],
       [ 5074.06775368],
       [ -139.57614828],
       [14592.9106523 ],
       [13694.7877942 ],
       [15591.75265438],
       [  533.99823592],
       [13865.33566852],
       [ 9870.90086271],
       [18169.84923808],
       [11747.92717393],
       [12700.07293688],
       [ 6601.86600794],
       [14663.52346228],
       [10008.8733277 ],
       [ 7969.94876397],
       [14573.72656862],
       [16131.19596087],
       [ 2108.02128429],
       [ 3395.10946871],
       [13502.76348645],
       [ 7290.90036633],
       [12026.31489456],
       [19616.8608733 ],
       [ 9023.80210542],
       [15805.40837156],
       [ 9080.18724761],
       [ 6851.95854817],
       [11336.85515756],
       [11115.78565937],
       [ 4763.02073907],
       [11312.8863058 ],
       [ 3234.44020863],
       [13171.60561026],
       [ 4715.93484045],
       [13361.66055171],
       [17750.65573593],
       [13106.28758163],
       [-2184.24439321],
       [16003.70167459],
       [12104.28833361],
       [ 3526.7424809 ],
       [ 3268.52860134]])

In [16]:
x_test

,age,income,purchase_frequency,gender_Male,education_High School,education_Master,education_PhD
25,56,36311,0.4,True,True,False,False
464,28,71517,0.8,False,False,False,False
372,50,82208,0.2,True,True,False,False
730,45,27374,0.3,False,False,False,True
757,21,32382,1.0,True,True,False,False
...,...,...,...,...,...,...,...
278,22,36169,0.1,False,True,False,False
449,50,52635,0.8,True,False,False,True
221,47,41270,0.7,True,False,True,False
741,51,38324,0.1,True,False,False,True
572,48,32913,0.2,True,False,True,False

In [17]:
y_test

      spending
25    5526.220
464  13260.680
372   2822.080
730   6410.610
757   6619.100
..         ...
278    880.845
449  16505.400
221  11944.450
741   2191.620
572   3329.130

[200 rows x 1 columns]

In [18]:
from sklearn.metrics import r2_score 
percentage=r2_score(y_test,y_pred)*100
print(f"result: {percentage} %")

result: 93.49355417351158 %

In [19]:
import pickle

filename = "spending.sav"

pickle.dump(regressor, open(filename, "wb"))


loaded_model = pickle.load(open(filename, "rb"))

In [20]:
age = int(input("Enter age: "))

gender = input("Enter gender (Male/Female): ").lower()

education = input("Enter education (High School/Bachelor/Master/PhD): ").lower()

income = float(input("Enter income: "))

purchase_frequency = float(input("Enter purchase frequency: "))

if gender == "male":
    gender_male = 1
else:
    gender_male = 0


if education == "high school":
    education_high_school = 1
    education_master = 0
    education_phd = 0

elif education == "master":
    education_high_school = 0
    education_master = 1
    education_phd = 0

elif education == "phd":
    education_high_school = 0
    education_master = 0
    education_phd = 1

elif education == "bachelor":
    education_high_school = 0
    education_master = 0
    education_phd = 0

else:
    print("Invalid education")
    exit()
import pandas as pd
prediction_input = pd.DataFrame([[
    age,
    income,
    purchase_frequency,
    gender_male,
    education_high_school,
    education_master,
    education_phd
]], columns=[
    "age",
    "income",
    "purchase_frequency",
    "gender_Male",
    "education_High School",
    "education_Master",
    "education_PhD"
])


result = loaded_model.predict(prediction_input)

predicted_spending = result[0][0]

print(f"For {age} year old {gender.title()} with {education.title()} education spending is {predicted_spending:.2f}")

Enter age:  52
Enter gender (Male/Female):  female
Enter education (High School/Bachelor/Master/PhD):  phd
Enter income:  5822
Enter purchase frequency:  0.9

For 52 year old Female with Phd education spending is 17709.40